config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'lists#index'
  resources :movies, only: :index do
    resources :bookmarks, only: %i[new create]
  end

  resources :lists, only: %i[index new create show]

  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :list, presence: true, uniqueness: { scope: :movie }
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  def self.search_ext(query)
    if query
      if self.where('title LIKE ?', "%#{query}%").empty?
        self.api_query(query)
        self.where('title LIKE ?', "%#{query}%")
      else
        self.where('title LIKE ?', "%#{query}%")
      end
    else
      self.all
    end
  end

  def self.api_query(query)
    # Get search word
    # build url
    url = "https://tmdb.lewagon.com/search/movie?query=#{query}."
    # request api
    api_answer = URI.open(url).read
    # parse data
    json = JSON.parse(api_answer)
    # build and return model
    json['results'].each do |result|
      movie_result = Movie.new(
        title: result['title'], overview: result['overview'], rating: result['vote_average'],
        poster_url: "https://image.tmdb.org/t/p/w400/#{result['poster_path']}"
      )
      movie_result.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_movie, only: [:create, :new]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(comment: bookmark_params[:comment])
    @list = List.find(bookmark_params[:list])
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.list, status: :see_other
  end

  private

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
require 'Open-URI'

class MoviesController < ApplicationController
  def index
    @movies = Movie.search_ext(params[:query])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-6">
      <img class="poster-banner" src="<%= @movie.poster_url %>" alt="">
    </div>
    <div class="col-6">
      <h1>Bookmark <%= @movie.title %></h1>
      <%= simple_form_for [@movie, @bookmark] do |f|%>
        <%= f.input :list, collection: List.all %>
        <%= f.input :comment %>
        <%= f.button :submit, class: "btn btn-primary" %>
        <%= link_to "back to Movies", movies_path, class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar-lewagon">
      <div class="row w-100 align-items-center mx-0">
        <div class="col-4 px-0">
          <div class="w-100">
            <%= link_to "All Movies", movies_path, class: "btn btn-primary" %>
          </div>
        </div>
        <div class="col-4 px-0">
          <div class="w-100 d-flex justify-content-center">
            <%= link_to "Watchlists", lists_path, class: "logo-font ms-3" %>
          </div>
        </div>
        <div class="col-4 px-0">
          <div class="w-100 d-flex justify-content-end">
            <%= link_to "Add List", new_list_path, class: "btn btn-success ms-2" %>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/_movie_card.html.erb
<div class="col-3">
  <div class="card w">
    <img src="<%= movie.poster_url %>" alt="">
    <div class="card-body">
      <h4><%= movie.title %> ️ <%= movie.rating %> ⭐️</h4>
      <p><%= movie.overview %></p>
    </div>
        <p class="btn btn-outline-warning mx-2"><%= movie.bookmarks.first.comment %></p>
    <div class="card-footer">
      <h5>Bookmark</h4>
      <%= link_to "Delete", bookmark_path(movie.bookmarks.first), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{movie.title} from this list?"}, class: "btn btn-danger" %>
      <%= link_to "Add", new_movie_bookmark_path(movie), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="container">
  <div class="d-flex my-3">
    <h1>All our Movielists(<%= @lists.length %>)</h1>
  </div>
  <div>
    <% @lists.each do |list| %>
      <div class="row">
        <div class="col-12 mt-4">
          <h2><%= link_to list.name, list_path(list), class: "text-decoration-none text-color-black" %></h2>
        </div>
        <% list.movies.first(2).each do |movie| %>
          <%= render "movie_card", movie: movie %>
        <% end %>
      </div>
    <% end %>
    <div class="col-12 mt-4">
      <%= link_to "Add a list", new_list_path, class: "btn btn-primary w-100 mb-5" %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <h1>Add a list</h1>
      <%# <p>Find me in app/views/lists/new.html.erb</p> %>
      <%= simple_form_for @list do |f|%>
        <%= f.input :name %>
        <%= f.button :submit, class: "btn btn-primary" %>
        <%= link_to "back to Lists", lists_path, class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>
  <div class="row">
    <% @list.movies.each do |movie| %>
      <%= render "movie_card", movie: movie %>
    <% end %>
  </div>
</div>

app/views/movies/_movie_card.html.erb
<div class="col-4">
  <div class="card w">
    <img src="<%= movie.poster_url %>" alt="">
    <div class="card-body">
      <h4><%= movie.title %> ️ <%= movie.rating %> ⭐️</h4>
      <p><%= movie.overview %></p>
      <div>
        <% movie.lists.each do |list| %>
          <%= link_to list.name, list_path(list), class: "btn btn-warning rounded-4 p-1" %>
        <% end %>
      </div>
    </div>
    <div class="card-footer">
      <%= link_to "Bookmark", new_movie_bookmark_path(movie), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container">
<h1>All Movies</h1>
<p>Welcome to WatchList. Inspiration for your first Watch-List</p>
  <div class="row mb-5">
    <form>
      <div class="d-flex">
        <input type="text" type="search" class="form-control" name="query" id="search-form" placeholder="Find a movie" value="<%= params[:query] %>">
        <input type="submit" class="btn btn-success ms-3" value="Search">
      </div>
    </form>
  </div>
  <div class="row">
    <% unless @movies.nil? %>
      <% @movies.each do |movie| %>
        <%= render "movie_card", movie: movie %>
      <% end %>
    <% end %>
  </div>
</div>